version: "3.9"

services:
  moodle:
    build: .
    container_name: moodle_app
    volumes:
      - moodledata:/var/www/moodledata
      - moodleconfig:/var/www/html/
volumes:
  moodledata:
  moodleconfig:
